### ISSUE TITLE
Add uptime monitor, log to log files

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-cw#36]
Add config options and associated code to Butler CW:

```
  # Uptime monitor
  uptimeMonitor:
    enabled: true                   # Should uptime messages be written to the console and log files?
    frequency: every 15 seconds     # https://bunkat.github.io/later/parsers.html
    logLevel: verbose               # Starting at what log level should uptime messages be shown?
```
