### ISSUE TITLE
Log uptime and memory usage to InfluxDB

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-cw#37]
Store Butler CW's memory usage to InfluxDB, similar to how Butler SOS does this. 

This will require a fair amount of new code in Butler CW, as well as new options in the main config file.
Something like this:

```
  # Uptime monitor
  uptimeMonitor:
    enabled: true                   # Should uptime messages be written to the console and log files?
    frequency: every 15 seconds     # https://bunkat.github.io/later/parsers.html
    logLevel: verbose               # Starting at what log level should uptime messages be shown?
    influxdb: 
      enabled: true    # Should data on Butler CW's own memory use be stored in Influxdb?
      hostIP: <IP or FQDN of Influxdb server>
      hostPort: <Port where Influxdb is listening>    # Optional. Default value=8086
      auth:
        enable: false                 # Does influxdb instance require authentication (true/false)?
        username: <username>          # Username for Influxdb authentication. Mandatory if auth.enable=true
        password: <password>          # Password for Influxdb authentication. Mandatory if auth.enable=true
      dbName: SenseOps
      # Default retention policy that should be created in InfluxDB when Butler CW creates a new database there. 
      # Any data older than retention policy threshold will be purged from InfluxDB.
      retentionPolicy:
        name: 2_weeks
        duration: 2w
        instanceTag: DEV              # Tag that can be used to differentiate data from multiple Butler CW instances

```
